import React from 'react';
import { storiesOf } from '@storybook/react';
import Modal from '../src/components/Modal/Modal';
import Button from '../src/components/Button/Button';

class ModalWithState extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      visible: false,
    };
  }

  render() {
    return (
      <div>
        <Modal visible={this.state.visible} minWidth={400}>
          OMG LOL
        </Modal>
        <Button onClick={() => this.setState({ visible: true })}>Open</Button>
      </div>
    );
  }
}

storiesOf('Modal', module)
  .add('primary', () => (
    <Modal visible>
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
      OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG
      LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL OMG LOL
    </Modal>
  ))
  .add('click to open', () => <ModalWithState />)
  .add('with action buttons', () => (
    <Modal
      title="Hi there!"
      visible
      actions={[<Button>Done</Button>, <Button type="secondary">Cancel</Button>]}
    />
  ));
